const fs = require('fs');
const path = require('path');
const { parse } = require('csv-parse/sync');

const DATA_DIR = path.resolve(__dirname, '../../scripts/etl/data');
const MAX_AUTOGENERATED_CODES = 1000;

function fileExists(fileName) {
  return fs.existsSync(path.join(DATA_DIR, fileName));
}

function readCsv(fileName) {
  const filePath = path.join(DATA_DIR, fileName);
  if (!fs.existsSync(filePath)) {
    return [];
  }

  const content = fs.readFileSync(filePath, 'utf8');
  return parse(content, {
    columns: true,
    skip_empty_lines: true,
    trim: true
  });
}

function pickColumn(headers, candidates) {
  if (!headers || headers.length === 0) return null;
  const lower = headers.map(h => (h || '').toLowerCase());
  for (const candidate of candidates) {
    const idx = lower.indexOf(candidate.toLowerCase());
    if (idx >= 0) {
      return headers[idx];
    }
  }
  return null;
}

function loadCIE10() {
  const candidates = ['cie10_colombia.csv', 'cie10_subset.csv'];
  let rows = [];
  let source = null;
  for (const file of candidates) {
    if (fileExists(file)) {
      rows = readCsv(file);
      source = file;
      break;
    }
  }

  if (!rows || rows.length === 0) {
    const dirEntries = fs.readdirSync(DATA_DIR);
    const singleColFiles = dirEntries.filter(name => name.startsWith('cie10_autogen_') && name.endsWith('.txt'));
    if (singleColFiles.length > 0) {
      const fileName = singleColFiles.sort().reverse()[0];
      const filePath = path.join(DATA_DIR, fileName);
      console.log(`[Terminology][Local] Generando CIE10 desde ${fileName} (FHIR ValueSet autogen)`);
      const lines = fs
        .readFileSync(filePath, 'utf8')
        .split(/\r?\n/)
        .map(line => line.trim())
        .filter(line => line.length > 0);

      const concepts = lines.map(line => {
        const match = line.split(/\s+/);
        const code = match[0];
        const display = line.substring(code.length).trim().replace(/^[-–—\s]+/, '');
        return { code, display: display || code };
      });

      if (concepts.length > 0) {
        console.log(`[Terminology][Local] CIE10 autogenerado: ${concepts.length} códigos`);
        const csvContent = ['code,display', ...concepts.map(c => `${c.code},"${c.display.replace(/"/g, '""')}"`)].join('\n');
        const outFile = path.join(DATA_DIR, `cie10_autogen_${Date.now()}.csv`);
        fs.writeFileSync(outFile, csvContent, 'utf8');
        return concepts;
      }
    }
    console.warn('[Terminology][Local] No se encontraron archivos CIE10 para fallback');
    return [];
  }

  const headers = Object.keys(rows[0] || {});
  const codeCol = pickColumn(headers, ['codigodx', 'codigo', 'code', 'cod_cie10', 'cie10']);
  const descCol = pickColumn(headers, ['descripciondx', 'descripcion', 'display', 'desc_cie10', 'diagnostico']);

  if (!codeCol || !descCol) {
    console.warn('[Terminology][Local] Columnas CIE10 no detectadas en', source);
    return [];
  }

  const items = rows
    .map(row => ({
      code: String(row[codeCol] || '').trim(),
      display: String(row[descCol] || '').trim(),
      system: 'http://hl7.org/fhir/sid/icd-10'
    }))
    .filter(item => item.code && item.display);

  console.log(`[Terminology][Local] CIE10 cargado (${items.length} registros) desde ${source}`);
  return items;
}

function loadMedications() {
  const candidates = ['cum_medicamentos.csv', 'meds_subset.csv'];
  let rows = [];
  let source = null;

  for (const file of candidates) {
    if (fileExists(file)) {
      rows = readCsv(file);
      source = file;
      break;
    }
  }

  if (!rows || rows.length === 0) {
    console.warn('[Terminology][Local] No se encontraron archivos de medicamentos para fallback');
    return [];
  }

  const headers = Object.keys(rows[0] || {});
  const codeCol = pickColumn(headers, [
    'expedientecum',
    'consecutivocum',
    'codigo_cum',
    'expediente',
    'codigo',
    'registrosanitario',
    'ium'
  ]);

  const displayCol = pickColumn(headers, [
    'descripcioncomercial',
    'producto',
    'presentacion',
    'descripcion',
    'nombre'
  ]);

  const atcCol = pickColumn(headers, ['atc', 'codigoatc', 'desc_atc', 'descripcionatc']);

  if (!codeCol || !displayCol) {
    console.warn('[Terminology][Local] Columnas de medicamentos no detectadas en', source);
    return [];
  }

  const system = 'https://terminology.salud.gov.co/medicamentos/invima';

  const items = rows
    .map(row => {
      const code = String(row[codeCol] || '').trim();
      const display = String(row[displayCol] || '').trim();
      let designation;
      if (atcCol && row[atcCol]) {
        const atcValue = String(row[atcCol]).trim();
        if (atcValue) {
          designation = [
            {
              language: 'es',
              use: {
                system: 'http://terminology.hl7.org/CodeSystem/designation-use',
                code: 'synonym'
              },
              value: `ATC ${atcValue}`
            }
          ];
        }
      }
      return {
        code,
        display,
        system,
        designation
      };
    })
    .filter(item => item.code && item.display);

  console.log(`[Terminology][Local] CUM cargado (${items.length} registros) desde ${source}`);
  return items;
}

// Cargar datos al iniciar el módulo
const localCIE10 = loadCIE10();
const localMeds = loadMedications();

function filterItems(items, query, limit = 20) {
  if (!query || query.length < 2) return [];
  const normalized = query.toLowerCase();
  return items
    .filter(item => {
      const codeMatch = item.code.toLowerCase().includes(normalized);
      const displayMatch = item.display.toLowerCase().includes(normalized);
      return codeMatch || displayMatch;
    })
    .slice(0, limit);
}

function searchCIE10(query, limit) {
  return filterItems(localCIE10, query, limit);
}

function searchMedications(query, limit) {
  return filterItems(localMeds, query, limit);
}

module.exports = {
  searchCIE10,
  searchMedications
};